# Generated by Django 6.0 on 2026-06-21 14:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvesting_date', models.DateField()),
                ('quantity_harvested', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True)),
                ('planting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='crops.planting')),
            ],
        ),
    ]
