# Generated by Django 6.0 on 2026-06-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(max_length=50)),
                ('customer_location', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True, verbose_name='Description or notes-to-self about the customer, e.g. stingy/mbahili, or maybe stubborn? 🙂')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
