# Generated by Django 6.0 on 2026-06-21 14:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100, unique=True, verbose_name='Specific name for crop')),
                ('maturity_days', models.PositiveIntegerField()),
                ('unit', models.CharField(max_length=20, verbose_name='Physical measurement unit')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, unique=True, verbose_name='Name of field/plot/block')),
                ('field_size', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Field size in acres')),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Planting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planting_qty_unit', models.CharField(max_length=20, verbose_name='Planting quantity, e.g. seeds, kg, etc.')),
                ('quantity_planted', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('planting_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plantings', to='crops.crop')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plantings', to='crops.field')),
            ],
        ),
    ]
