# Generated by Django 6.0.7 on 2026-10-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='maturity_days',
            field=models.PositiveIntegerField(verbose_name='Maturity period in days'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='unit',
            field=models.CharField(choices=[('g', 'Gram (g)'), ('kg', 'Kilogram (kg)'), ('tonne', 'Tonne'), ('bag', 'Bag'), ('crate', 'Crate'), ('bunch', 'Bunch'), ('heads', 'Heads'), ('pcs', 'Pieces (pcs)')], max_length=20, verbose_name='Harvest and sales unit'),
        ),
    ]
